config/routes.rb
Hapful::Application.routes.draw do

  get "user_payment_methods/index"
  get "user_payment_methods/new"
  get "user_payment_methods/edit"
  get "paypal_accounts/index"
  get "paypal_accounts/edit"

  namespace :admin do 
    resources :categories
    resources :articles
    resources :payment_types
    resources :shipping_options
    resources :project_configs
    resources :users do
      member do
        post :tag
      end
    end
    resources :products
    resources :custom_emails
    root :to => 'dashboard#index'
  end

  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
  end

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  resources :users do
    member do
      get :change_password
      post :update_password
      get :merchant_detail
      match :update_merchant_detail
    end
    resources :user_merchant_accounts, :path=>:merchaccounts
    resources :user_payment_methods, :path=>:paygates
  end
  
  resources :taxes do
    collection do
      post :save
    end
  end

  resources :products do
    resources :product_widgets do
      member do
        get :preview
        get :iframed
      end
    end
    resources :comments do
      member do
        get :vote
      end
    end
    member do
      get :demo
    end
  end

  match '/posts/(:action)', :controller=>:posts

  resources :orders do
    member do
      get :change_state
    end
  end

  match '/my-dashboard' => 'users#dashboard', :as=>:user_dashboard

  match '/add-to-cart/:product_slug' =>'carts#add',   :as=>:add_to_cart
  match '/cart/cq/:product_slug/:change' =>'carts#change_quantity', :as=>:change_quantity
  match '/my-cart'                    =>'carts#show', :as=>:show_cart
  match '/trial' => 'pages#trial', :as=>:trial

  match  '/checkout/payment_state/:state'=> 'payments#set_state',               :as=>:set_payment_state
  match '/checkout/notice'            => 'payments#manual',                     :as=>:payment_notice
  get   '/checkout/payment'           => 'payments#new',                      :as=>:payment_checkout
  post  '/checkout/payment'           => 'payments#create',                   :as=>:do_payment_checkout
  get   '/checkout/complete_ppexpress'=> 'payments#complete_paypal_express',  :as=>:complete_paypal_express
  get   '/checkout/:merchant'         => 'orders#new',                        :as=>:checkout
  post  '/checkout/:merchant'         => 'orders#create',                     :as=>:build_order

  get '/track/:reference_number'    =>'pages#order_tracking', :as=>:order_tracking
  post '/track/:reference_number'    =>'pages#view_order_tracking', :as=>:view_order_tracking

  match '/update_merch' => 'pages#update_merch'
  match '/c/:id' => 'pages#by_category', :as=>:by_category
  match '/market' => 'pages#market', :as=>:market
  match '/search' => 'pages#search', :as=>:search
  match '/complete' => 'orders#completed', :as=>:completed_order
 
  match '/paypal-express' => 'payments#paypal_express', :as=>:paypal_express_checkout
  put '/redirect/:url' => 'pages#redirection'
  match '/p/:id' => 'products#show'
  match '/s/:seller'  =>'pages#seller', :as=>:seller_page
  match '/faqs' => 'pages#faqs', :as=>:faqs
  match '/privacy_policy' => 'pages#privacy_policy', :as=>:privacy_policy
  match '/terms' => 'pages#terms', :as=>:terms

  #  scope :protocol => 'https://', :constraints => { :protocol => 'https://' } do
  #    match '/paypal-express' => 'payments#paypal_express', :as=>:paypal_express_checkout
  #  end
  
  root :to=>'pages#index'

end

app/views/shared/_flash_messages.html.erb
<div id="flash-banner">
  <% flash.each do |key, msg| %>
    <%= content_tag :div, msg, :class => "flash " + key.to_s, :id => key.to_s + "-message" %>
    <%= content_tag :script, :type => "text/javascript" do %>
      $('.flash.<%= key.to_s %>').css('display', 'none');
      $('.flash.<%= key.to_s %>').slideDown().delay(3000).slideUp();
    <% end %>
  <% end %>
</div>

app/views/shared/_footer.html.haml
#footer
  ©2012. All Rights Reserved
  \|
  = link_to 'Privacy Policy', '/privacy_policy'
  \|
  = link_to 'Terms', '/terms'

app/views/shared/_form_errors.html.haml
- if object.errors.any?
  #form_errors
    /%h4= "#{pluralize(object.errors.count, "error")} prohibited this #{object.class.to_s.humanize.downcase} from being saved:"
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_product_image.html.haml
.image_holder
  = link_to image_tag(product.images.first.image(:thumbnail)), product.redirection_path
  .price
    = number_to_currency product.price
  .image_title
    = link_to product.name, product.redirection_path
    %br
    by
    %span
      = link_to product.seller.username, "/s/#{product.seller.username}"
    %br
    - if controller_name != "comments"
      %span
        = link_to "view comments", product_comments_path(product)

app/views/shared/_show_post.html.haml
.post-container
  .post-title
    = link_to post.name, post.post_url
  .right
    %strong
      Price:
      = number_to_currency(post.price)
  .clear
  By:
  = post.user.username
  %br
  = link_to "Comments (#{post.comment_threads.count})", product_comments_path(post)
  