config/routes.rb
Hapful::Application.routes.draw do

  get "user_payment_methods/index"
  get "user_payment_methods/new"
  get "user_payment_methods/edit"
  get "paypal_accounts/index"
  get "paypal_accounts/edit"

  namespace :admin do 
    resources :categories
    resources :articles
    resources :payment_types
    resources :shipping_options
    resources :project_configs
    resources :users do
      member do
        post :tag
      end
    end
    resources :products
    resources :custom_emails
    root :to => 'dashboard#index'
  end

  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
  end

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  resources :users do
    member do
      get :change_password
      post :update_password
      get :merchant_detail
      match :update_merchant_detail
    end
    resources :user_merchant_accounts, :path=>:merchaccounts
    resources :user_payment_methods, :path=>:paygates
  end
  
  resources :taxes do
    collection do
      post :save
    end
  end

  resources :products do
    resources :product_widgets do
      member do
        get :preview
        get :iframed
      end
    end
    resources :comments do
      member do
        get :vote
      end
    end
    member do
      get :demo
    end
  end

  match '/posts/(:action)', :controller=>:posts

  resources :orders do
    member do
      get :change_state
    end
  end

  match '/my-dashboard' => 'users#dashboard', :as=>:user_dashboard

  match '/add-to-cart/:product_slug' =>'carts#add',   :as=>:add_to_cart
  match '/cart/cq/:product_slug/:change' =>'carts#change_quantity', :as=>:change_quantity
  match '/my-cart'                    =>'carts#show', :as=>:show_cart
  match '/trial' => 'pages#trial', :as=>:trial

  match  '/checkout/payment_state/:state'=> 'payments#set_state',               :as=>:set_payment_state
  match '/checkout/notice'            => 'payments#manual',                     :as=>:payment_notice
  get   '/checkout/payment'           => 'payments#new',                      :as=>:payment_checkout
  post  '/checkout/payment'           => 'payments#create',                   :as=>:do_payment_checkout
  get   '/checkout/complete_ppexpress'=> 'payments#complete_paypal_express',  :as=>:complete_paypal_express
  get   '/checkout/:merchant'         => 'orders#new',                        :as=>:checkout
  post  '/checkout/:merchant'         => 'orders#create',                     :as=>:build_order

  get '/track/:reference_number'    =>'pages#order_tracking', :as=>:order_tracking
  post '/track/:reference_number'    =>'pages#view_order_tracking', :as=>:view_order_tracking

  match '/update_merch' => 'pages#update_merch'
  match '/c/:id' => 'pages#by_category', :as=>:by_category
  match '/market' => 'pages#market', :as=>:market
  match '/search' => 'pages#search', :as=>:search
  match '/complete' => 'orders#completed', :as=>:completed_order
 
  match '/paypal-express' => 'payments#paypal_express', :as=>:paypal_express_checkout
  put '/redirect/:url' => 'pages#redirection'
  match '/p/:id' => 'products#show'
  match '/s/:seller'  =>'pages#seller', :as=>:seller_page
  match '/faqs' => 'pages#faqs', :as=>:faqs
  match '/privacy_policy' => 'pages#privacy_policy', :as=>:privacy_policy
  match '/terms' => 'pages#terms', :as=>:terms

  #  scope :protocol => 'https://', :constraints => { :protocol => 'https://' } do
  #    match '/paypal-express' => 'payments#paypal_express', :as=>:paypal_express_checkout
  #  end
  
  root :to=>'pages#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def add
    @product = Product.find_by_slug(params[:product_slug])
    cart_sellers = Marshal.load(cookies["#{cookies["_hapful_session"]}-sellers".to_sym]) rescue []
    cart_contents = Marshal.load(cookies["#{cookies["_hapful_session"]}-#{@product.user_id}".to_sym]) rescue {}
    cart_sellers << @product.user_id
    cart_sellers.uniq!
    new_item_key = "p_#{@product.id}_v_#{params[:cart][:product_option_id]}"

    ## NOTE: product and option is already existing
    if cart_contents.keys.include?(new_item_key)

      ## Buyer clicks the up and down arrow on the orders table
      cart_contents[new_item_key][:quantity] = if params[:change].eql?('down')
        if cart_contents[new_item_key][:quantity].to_i - params[:cart][:quantity].to_i < 1
          flash[:error] = "Quantity is not allowed"
          return redirect_to show_cart_path
        end
        cart_contents[new_item_key][:quantity].to_i - params[:cart][:quantity].to_i
      else
        params[:cart][:quantity].to_i + cart_contents[new_item_key][:quantity].to_i
      end

    ## NOTE: product and option net yet on cart
    else
      initial_quantity = params[:cart][:quantity] || 1
      cart_contents[new_item_key]={
        :quantity=>initial_quantity.to_i,
        :product_option_id=>params[:cart][:product_option_id],
        :product_id=>@product.id
      }
    end
    
    cookies["#{cookies["_hapful_session"]}-#{@product.user_id}".to_sym] = {
      :value => Marshal.dump(cart_contents),
      :expires => 4.years.from_now
    }
    cookies["#{cookies["_hapful_session"]}-sellers".to_sym] = {
      :value => Marshal.dump(cart_sellers),
      :expires => 4.years.from_now
    }
    
    redirect_to show_cart_path
  end

  def show
    build_objects_from_cookies
    respond_to do |format|
      format.html{render :layout=>false if params[:cbed]}
      format.js {render :layout=>false}
    end
  end


  def remove_content

  end

end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/carts/_cart_per_seller.html.haml
%h4
  Products ordered from
  = seller.username
%table
  %thead
    %tr
      %th Product
      %th Price
      %th Quantity
      %th Total
  - total_amount = 0.0
  - cart.each do |item|
    %tr
      %td
        = item[:product].name
        - if !item[:product_option_id].blank?
          = "(#{item[:variant].description})"
      %td
        = number_to_currency(item[:product].effective_price)
        - if !item[:product_option_id].blank?
          = "(+#{ number_to_currency(item[:variant].additional_cost.to_f )})" if item[:variant].additional_cost.to_f != 0.0
      %td
        %span{:pv=>item[:product_option_id]}
          - ret_url = params[:controller]=='orders' ? checkout_path(seller.username) : '/my-cart'
          = link_to_function "+", |
            "change_quantity('#{add_to_cart_path(item[:product].slug)}', '#{ret_url}', '#{item[:product_option_id]}', 'up')", |
            {:class=>"greenCharBtn"}
        = text_field_tag "item[quantity]", item[:quantity], :style=>'width: 50px; text-align: right'
        - if item[:quantity] > 1
          %span{:pv=>item[:product_option_id], :mv=>'down'}
          = link_to_function "-", |
            "change_quantity('#{add_to_cart_path(item[:product].slug)}', '#{ret_url}', '#{item[:product_option_id]}', 'down')", |
            {:class=>"greenCharBtn"}
      %td
        - item_amount = item[:quantity] * (item[:product].effective_price.to_f + item[:variant].additional_cost.to_f )
        - total_amount += item_amount
        = number_to_currency(item_amount)
  %tr
    %td{:colspan=>3}
      %strong.right TOTAL
    %td
      %strong{:style=>"font-size: 16px"}= number_to_currency(total_amount)

- unless params[:controller] == 'orders'
  - if params[:demo]
    DEMO purposes
  - else
    - if params[:cbed]
      = link_to "CHECKOUT",'#', :class=>"greenBtn", :onclick=>"window.top.location.href = '#{ProjectConfig.value('site_url')}#{url_for(checkout_path(seller.username))}';"
      = link_to "Continue Shopping", '#', :onclick=>"$('#product-trigger').trigger('click')"
    - else
      = link_to "Checkout cart for #{seller.username}", checkout_path(seller.username), :class=>"redBtn"
      = link_to "Continue Shopping", market_path

app/views/carts/_order_table.haml
- @cart.each do |seller, cart|
  = render :partial=>'cart_per_seller', :locals=>{:cart=>cart, :seller=>seller}
    

app/views/carts/show.html.haml
- if @cart.empty?
  Your shopping cart is empty.
  - if params[:cbed]
    = link_to "Shop Now!", '#', :onclick=>"$('#product-trigger').trigger('click')"
  - else
    = link_to "Shop Now!", market_path, :class=>'redBrick'


- else
  - if params[:seller]
    - seller = User.find(params[:seller])
    = render :partial=>'cart_per_seller', :locals=>{:cart=>@cart[seller], :seller=>seller}
  - else
    = render 'order_table'

app/views/carts/show.js.erb
$('#cart-trigger').trigger('click')