config/routes.rb
Hapful::Application.routes.draw do

  get "user_payment_methods/index"
  get "user_payment_methods/new"
  get "user_payment_methods/edit"
  get "paypal_accounts/index"
  get "paypal_accounts/edit"

  namespace :admin do 
    resources :categories
    resources :articles
    resources :payment_types
    resources :shipping_options
    resources :project_configs
    resources :users do
      member do
        post :tag
      end
    end
    resources :products
    resources :custom_emails
    root :to => 'dashboard#index'
  end

  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
  end

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  resources :users do
    member do
      get :change_password
      post :update_password
      get :merchant_detail
      match :update_merchant_detail
    end
    resources :user_merchant_accounts, :path=>:merchaccounts
    resources :user_payment_methods, :path=>:paygates
  end
  
  resources :taxes do
    collection do
      post :save
    end
  end

  resources :products do
    resources :product_widgets do
      member do
        get :preview
        get :iframed
      end
    end
    resources :comments do
      member do
        get :vote
      end
    end
    member do
      get :demo
    end
  end

  match '/posts/(:action)', :controller=>:posts

  resources :orders do
    member do
      get :change_state
    end
  end

  match '/my-dashboard' => 'users#dashboard', :as=>:user_dashboard

  match '/add-to-cart/:product_slug' =>'carts#add',   :as=>:add_to_cart
  match '/cart/cq/:product_slug/:change' =>'carts#change_quantity', :as=>:change_quantity
  match '/my-cart'                    =>'carts#show', :as=>:show_cart
  match '/trial' => 'pages#trial', :as=>:trial

  match  '/checkout/payment_state/:state'=> 'payments#set_state',               :as=>:set_payment_state
  match '/checkout/notice'            => 'payments#manual',                     :as=>:payment_notice
  get   '/checkout/payment'           => 'payments#new',                      :as=>:payment_checkout
  post  '/checkout/payment'           => 'payments#create',                   :as=>:do_payment_checkout
  get   '/checkout/complete_ppexpress'=> 'payments#complete_paypal_express',  :as=>:complete_paypal_express
  get   '/checkout/:merchant'         => 'orders#new',                        :as=>:checkout
  post  '/checkout/:merchant'         => 'orders#create',                     :as=>:build_order

  get '/track/:reference_number'    =>'pages#order_tracking', :as=>:order_tracking
  post '/track/:reference_number'    =>'pages#view_order_tracking', :as=>:view_order_tracking

  match '/update_merch' => 'pages#update_merch'
  match '/c/:id' => 'pages#by_category', :as=>:by_category
  match '/market' => 'pages#market', :as=>:market
  match '/search' => 'pages#search', :as=>:search
  match '/complete' => 'orders#completed', :as=>:completed_order
 
  match '/paypal-express' => 'payments#paypal_express', :as=>:paypal_express_checkout
  put '/redirect/:url' => 'pages#redirection'
  match '/p/:id' => 'products#show'
  match '/s/:seller'  =>'pages#seller', :as=>:seller_page
  match '/faqs' => 'pages#faqs', :as=>:faqs
  match '/privacy_policy' => 'pages#privacy_policy', :as=>:privacy_policy
  match '/terms' => 'pages#terms', :as=>:terms

  #  scope :protocol => 'https://', :constraints => { :protocol => 'https://' } do
  #    match '/paypal-express' => 'payments#paypal_express', :as=>:paypal_express_checkout
  #  end
  
  root :to=>'pages#index'

end

app/models/product.rb
class Product < ActiveRecord::Base

  STATES = %w(new saved expiring published deleted)
  STATES.each do |state|
    define_method "#{state}?" do
      self.state == state
    end
    define_method "mark_as_#{state}!" do
      self.state = state
      self.save
    end
  end

  extend FriendlyId
  friendly_id :name, :use => :slugged
  
  acts_as_taggable
  acts_as_commentable

  has_one :widget, :class_name=>'ProductWidget', :dependent=>:destroy
  
  has_many :options, :class_name=>'ProductOption', :dependent=>:destroy
  has_many :images, :class_name=>'ProductImage', :dependent=>:destroy
  has_many :order_items
  has_many :orders, :through=>:order_items
  has_many :payment_options, :class_name=>'ProductPaymentOption', :dependent=>:destroy
  has_many :shipping_options, :class_name=>'ProductShippingOption', :order=>"amount", :dependent=>:destroy do
    def for_option(option)
      find(:first, :conditions=>{:shipping_option_id=>option.id}) || ProductShippingOption.new
    end
  end
  has_many :payment_types, :through=>:payment_options,  :source=>:payment_type
  has_many :shipping_types, :through=>:shipping_options, :class_name=>'ShippingOption', :source=>:shipping_option

  accepts_nested_attributes_for :widget, :allow_destroy=>true
  accepts_nested_attributes_for :options,  :reject_if => proc{|attrs| attrs.all?{|k,v| k=='_destroy' ? v : v.blank?} }, :allow_destroy=>true
  accepts_nested_attributes_for :images, :allow_destroy=>true

  belongs_to :user
  belongs_to :category

  delegate :name, :to=>:category, :allow_nil=>true, :prefix=>true
  
  alias_method :seller, :user

  scope :top_rated, where({:state=>'active', :use_hapful=>true}, limit(10).order("rating DESC"))
  scope :newly_added, where({:state=>'active', :use_hapful=>true}, limit(10).order("created_at DESC"))
  scope :most_viewed, where({:state=>'active', :use_hapful=>true}, limit(10).order("views DESC"))
  scope :active, where(["state!='deleted' OR state IS NULL AND use_hapful=?", true])
  scope :deleted, where({:state=>'deleted'})
  scope :as_external, where({:is_external=>true})


  ## VALIDATIONS
  validates_presence_of :name
  validates_presence_of :price
  validates_presence_of :post_url
  validate :has_image?, :if=>:use_hapful?
  validate :check_payment_and_shipping, :if=>:use_hapful?

  ## CALLBACKS
  after_create [:create_code, :initialize_widget_data]
  
  def belongs_to?(user)
    self.user == user
  end

  def product_widget_path
    "#{ProjectConfig.value("site_url")}/p/#{slug}"
  end

  def embed_code(options={})
    %Q!<script src="#{product_widget_path}.js#{'?demo=1'if options[:demo]==true }"></script>!
  end

  def redirection_path
    post_url || "/products/#{slug}"
  end

  def effective_price
    amount = self.on_discount? ? discounted_price : price
  end

  def products_related_by_user(limit = 5)
    seller.products.find(:all, :limit=>limit, :conditions=>["id != ?", self.id])
  end

  def products_related_by_category(limit = 5)
    category.products.find(:all, :limit=>limit, :conditions=>["id != ?", self.id])
  end

  def self.paginated_search(opts, page, per_page, use_hapful=true)
    @opts = opts
    @use_hap = use_hapful ? 1 : 0
    self.paginate_by_sql(search_sql, :page=>page, :per_page=>per_page)
  end

  def self.paginated_search_count(opts, use_hapful=true)
    @opts = opts
    @use_hap = use_hapful ? 1 : 0
    self.count_by_sql(search_sql)
  end

  def self.search_sql
    sql_statement = "SELECT * FROM #{Product.table_name} WHERE "
    sql_statement << "name LIKE ? " if @opts[:keyword]
    sql_statement << "AND category_id = ?" if @opts[:category]
    sql_statement << "AND use_hapful = #{@use_hap} AND state != 'deleted' "
    ret_arr = [sql_statement]
    ret_arr << "%#{@opts[:keyword]}%" if @opts[:keyword]
    ret_arr << @opts[:category] if @opts[:category]
    ret_arr
  end

  def set_shipping_options(params)
    params.each do |k,v|
      obj = shipping_options.find(:first, :conditions=>{:shipping_option_id=>k})
      if obj
        v['shipping_option_id'].nil? ? obj.destroy : obj.attributes = v; obj.save
      else
        v['shipping_option_id'].nil? ? next : self.shipping_options.build(v)
      end
    end
  end

  def set_payment_options(params)
    self.payment_type_ids = params
  end

  private

  def initialize_widget_data
    widget = self.create_widget(:content=>"Quantity {{ quantity }}<br/>Image Gallery {{ image_gallery}}<br/>Options {{ options }}", :title=>"See the Product")
    self.state = "Widget needs updating" if self.customized_widget?
    ProductWidgetContent::BUILT_IN.each do |k,v|
      widget.contents.create!(:name=>k)
    end
  end

  def create_code
    self.code = Digest::SHA1.hexdigest("#{self.id}:#{self.name}")
    self.ordered_quantity = 0
    self.quantity = 0 if self.quantity.nil?
    save
  end

  def has_image?
    errors.add_to_base "Please upload at least 1 image" if self.images.blank? || self.images.first.image_file_name.blank?
  end

  def check_payment_and_shipping
    check_payment_options
    check_shipping_options
  end

  def check_payment_options
    if payment_types.blank?
      errors.add_to_base("Please select at least 1 payment option")
    end
  end

  def check_shipping_options
    errors.add_to_base("Please select at least 1 shipping option") if shipping_options.blank?
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  def index
    @products = Product.paginate(:page=>params[:page], :per_page=>15, :order=>"state desc")
    @deleted_products = Product.deleted
  end

  def destroy
    @product = Product.find(params[:id])
    @product.mark_as_deleted!
    redirect_to [:admin, :products]
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_filter :get_product, :except=>[:index, :new, :create]
  before_filter :user_access_restriction, :except=>[:index, :show, :new, :create]
  before_filter :merge_state_params, :only=>[:create, :update]

  def index
    if current_user
      @products = current_user.products
      @posts = current_user.posts
    else
      redirect_to market_path
    end
    render :layout=>false if params[:ajax]
  end

  def show
    @widget = @product.widget || @product.build_widget
    @content = @widget.content
    @demo = true if params[:demo]
    respond_to do |format|
      format.html
      format.js do
        @compiled_template = if @widget.embedded?
          render_to_string(:partial=>"product_widgets/embed")
        else
          render_to_string(:partial=>"product_widgets/colorbox")
        end
      end
    end
  end

  def new
    @product = current_user.products.new
    @product.images.build
    @product.options.build
    @product.build_widget
  end

  def edit
  end

  def create
    @product = current_user.products.new(params[:product])
    set_product_behavior
    respond_to do |format|
      if @product.save()
        format.html { redirect_to(seller_page_path(@product.user.username), :notice => 'Product was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    set_product_behavior
    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to(@product, :notice => 'Product was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to(products_url) }
      format.xml  { head :ok }
    end
  end

  def demo
    render :layout=>'frame'
  end
  

  private

  def get_product
    @product = Product.find(params[:id])
  end

  def user_access_restriction
    unless current_user == @product.user
      redirect_to request.referrer, :notice=>"You don't have access here"
    end
  end

  def merge_state_params
    state = if params[:commit].eql?("Save as Draft")
      {:state => "saved" }
    else
      {:state => "active" }
    end
    params[:product].merge!(state)
  end

  def set_shipping_and_payment
    @product.set_payment_options(params[:payopts]) if params[:payopts]
    @product.set_shipping_options(params[:shipopts]) if params[:shipopts]
  end

  def set_product_behavior
    if @product.use_hapful? || params[:product][:use_hapful].eql?('1')
      set_shipping_and_payment
    else
      @product.images = []
    end
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_buyer_view.html.haml
= form_for :cart, :url=>add_to_cart_path(@product) do |f|
  = render 'product_widgets/default_view'
  /- if @product.customized_widget?
  /  = raw compile_template
  /  = f.submit "Add to Cart", :class=>'greenBtn'
  /- else
  /  = render 'product_widgets/default_view'
%hr{:color=>"#cfcfcf"}
%h4 Other products from seller
- @product.products_related_by_user.each do |product|
  = product.name
%br
%h4 Products within the same category
- @product.products_related_by_category.each do |product|
  = product.name

app/views/products/_form.html.haml
= nested_form_for @product, :html=>{:class=>"", :multipart=>true} do |f|
  .nav_link
    = link_to "<< Back to Dashboard", '/my-dashboard'
  %br
  = render :partial=>'shared/form_errors', :locals=>{:object=>@product}
  %h2
    = f.object.new_record? ? 'Add' : 'Edit'
    Product
    .right
      - if @product.new_record?
        = f.submit 'Save and Publish', :class=>"greenBtn"
      - else
        = f.submit 'Update', :class=>"greenBtn"
  .clear
  #details
    = render :partial=>'product_fields', :locals=>{:f=>f}
  .right
    - if @product.new_record?
      = f.submit 'Save and Publish', :class=>"greenBtn"
    - else
      = f.submit 'Update', :class=>"greenBtn"
  .clear

app/views/products/_image_and_variants_form.html.haml
.halfcolright
  %fieldset.form{:style=>"min-height: 150px"}
    %legend
      %strong IMAGES
    = f.fields_for :images do |image_form|
      - if image_form.object.new_record?
        = image_form.file_field :image
      - else
        = image_tag image_form.object.image(:thumbnail)
      = image_form.link_to_remove image_tag("close.png")
    %strong= f.link_to_add "Add More Images", :images
.half
  %fieldset.form{:style=>"min-height: 150px; width: 100%"}
    %legend
      %strong VARIANTS
    %span.italic{:style=>"color: #7d7d7d"} (Create options like color, size, etc.)
    = f.fields_for :options do |option_form|
      %div{:style=>"border: 1px solid #095D92; background: #FFF; margin-bottom: 5px"}
        %table
          %tr
            %td
              %strong Description
            %td{:colspan=>2}= option_form.text_field :description, :size=>20
          %tr
            %td
              %strong Additional Cost
            %td{:colspan=>2}= option_form.text_field :additional_cost, :size=>8
          %tr
            %td
              %strong Quantity Available
            %td= option_form.text_field :quantity, :size=>8
            %td= option_form.link_to_remove image_tag("close.png")

    .clear
    %strong= f.link_to_add "Add Variant", :options
.clear
%br

app/views/products/_image_gallery.html.haml
#inline-content
  - @product.images.each do |image|
    = link_to image_tag("#{ProjectConfig.value('site_url')}#{image.image(:thumbnail)}"), "#{ProjectConfig.value('site_url')}#{image.image.url}", :class=>"colorbox-gallery"

app/views/products/_options.html.haml
- if @product.options.count > 0
  = select_tag "cart[product_option_id]", |
    options_for_select(@product.options.collect{|option| [option.description, option.id]}.insert(0, ["Pick a variant", '']) )

app/views/products/_product_fields.html.haml
%table.zebra
  %tr
    %td{:colspan=>2}
      %strong Product Title
      %br
      = f.text_field :name, :style=>'width: 95%'
  %tr
    %td{:colspan=>2}
      %strong
        Post URL
        %span.italic{:style=>"color: #7d7d7d"} (Paste in the URL of your blog post to create the link)
      %br
      = f.text_field :post_url, :size=>'70%'
  %tr
    %td{:style=>"width: 30%"}
      %strong Price
    %td= f.text_field :price, :size=>'8'
  %tr
    %td{:colspan=>2}
      = f.check_box :use_hapful, :onclick=>"$('#as-product').toggle()"
      = f.label :use_hapful, "Use Hapful to manage by product."
#as-product{:style=>"display: #{f.object.use_hapful? ? 'block' : 'none' }"}
  %table.zebra
    %tr
      %td{:style=>"width: 30%"}
        %strong Category
      %td
        = f.select :category_id, Category.all.collect{|category| [category.name, category.id]}
      %td
        %strong Available Units
      %td
        = f.text_field :quantity, :size=>'8'
    %tr
      %td{:colspan=>4}
        = f.check_box :on_discount, :onclick=>"$('#discount').toggle()"
        %strong
          = f.label :on_discount, 'Place item on discount'
    %tr{:id=>'discount', :style=>"#{f.object.on_discount? ? '' : 'display: none' }; width: 100%"}
      %td{:style=>"width: 30%"}
        %strong Discounted Price
      %td{:colspan=>3}= f.text_field :discounted_price, :size=>'8'
  .infobox
    = ProjectConfig.value("description_note")
  %br
  = render :partial=>'products/image_and_variants_form', :locals=>{:f=>f}
  = render :partial=>'products/shipping_and_payment_form', :locals=>{:f=>f}
  /= render :partial=>'products/widget_form', :locals=>{:f=>f}

app/views/products/_shipping_and_payment_form.html.haml
.halfcolright
  %fieldset.form
    %legend
      %strong SHIPPING OPTIONS
    %table
      - ShippingOption.active.each do |shipping_option|
        %tr
          %td= shipping_option.name
          %td{:style=>'width: 20px'}= check_box_tag "shipopts[#{shipping_option.id}]shipping_option_id", |
          shipping_option.id, f.object.shipping_type_ids.include?(shipping_option.id), |
          :onclick=>"toggleAmount(this,'#{shipping_option.id}')"
          %td Cost
          %td= text_field_tag "shipopts[#{shipping_option.id}]amount", |
          f.object.shipping_options.for_option(shipping_option).amount, :size=>5, :id=>"ship#{shipping_option.id}amt", |
          :disabled=>!f.object.shipping_type_ids.include?(shipping_option.id)
.half
  %fieldset.form
    %legend
      %strong PAYMENT OPTIONS
    %table
      - PaymentType.activated.each do |payment_type|
        %tr
          %td{:style=>'width: 20px'}= check_box_tag "payopts[]", |
          payment_type.id, f.object.payment_type_ids.include?(payment_type.id)
          %td= payment_type.name
.clear
%br
%script{:type=>"text/javascript"}
  function toggleAmount(obj,id){
  $('#ship' + id + 'amt').attr('disabled', !$(obj).is(':checked'))
  }

app/views/products/_show_details.html.haml
#details
  %table.zebra
    %tr
      %td Name
      %td.strong= @product.name
    %tr
      %td Price
      %td.strong= number_to_currency @product.price
      %td Discount Price
      %td.strong= number_to_currency @product.discounted_price
    %tr
      %td Category
      %td.strong
        = @product.category_name
        /- if @product.category.thatwayhat_integratable?
        /  = link_to "Integrate to Thatwayhat!", '', :class=>"greenBtn"
      %td Tags
      %td.strong= @product.tag_list.join(", ")
    %tr
      %td Embed Code
      %td{:colspan=>3}
        = text_area_tag :embed, @product.embed_code, |
        :style=>'width: 95%; height: 50px', :id=>'embed-code'
        %br
        .infobox
          Copy and Paste the code above to your blog post.
    %tr
      %td Shipping Options
      %td.strong= @product.shipping_options.collect(&:name).join(", ")
      %td Payment Options
      %td.strong= @product.payment_options.collect(&:name).join(", ")

  %h5 Images
  - @product.images.each do |image|
    = image_tag(image.image(:thumbnail))

app/views/products/_show_logistics.html.haml
#logistics
  %h5
    Quantity:
    = @product.quantity
    \|
    Ordered:
    = @product.ordered_quantity
    \|
    Total Left
    = @product.quantity - @product.ordered_quantity
  %table
    %thead
      %tr
        %th Order
        %th Order Status
        %th Quantity
      - @product.order_items.each do |item|
        %tr
          %td= item.order.reference_number
          %td= item.order.state.humanize
          %td= item.quantity

app/views/products/_widget_form.html.haml
#widget
  %fieldset.form
    = f.fields_for :widget do |widget_f|
      = f.hidden_field :customized_widget, :value=>true
      - widget_f.object.embedded = true if widget_f.object.new_record?
      %table{:id=>"customized_widget"}
        %tr
          %td{:colspan=>2}
            = widget_f.radio_button :embedded, true, :id=>'embed-true', :onclick=>"$('#widget-label').attr('disabled', true);"
            %strong= widget_f.label :embedded, 'Display product directly in blog', |
            :onclick=>"$('#embed-true').click();", :style=>"cursor: pointer"
            %br
            %br
            = widget_f.radio_button :embedded, false, :id=>'embed-false', :onclick=>"$('#widget-label').removeAttr('disabled');"
            %strong= widget_f.label :embedded, 'Display product in blog post using link that says', |
            :onclick=>"$('#embed-false').click();", :style=>"cursor: pointer"
            = widget_f.text_field :title, :id=>'widget-label', :disabled=>widget_f.object.embedded?

app/views/products/demo.html.haml
= raw @product.embed_code(:demo=>true)

app/views/products/index.html.haml
.clear
- unless params[:ajax]
  %h3 Product List
%br
#list
  %h3 Products
  %table.zebra
    %thead
      %tr
        %th Name
        %th Options
    - @products.each do |product|
      %tr
        %td= link_to product.name, product
        %td
          /= link_to 'Widget', [:edit, product, product.widget] #disbaled for now
          /\|
          = link_to 'Edit', edit_product_path(product)
          \|
          = link_to 'Delete', product, :confirm => 'Are you sure?', :method => :delete
  %h3 Posts
  %table.zebra
    %thead
      %tr
        %th Name
        %th Options
    - @posts.each do |post|
      %tr
        %td= link_to post.name, post
        %td
          /= link_to 'Widget', [:edit, product, product.widget] #disbaled for now
          /\|
          = link_to 'Edit', edit_product_path(post)
          \|
          = link_to 'Delete', post, :confirm => 'Are you sure?', :method => :delete

app/views/products/show.html.haml
- if @product.deleted?
  %h2
    This product has been deleted by Hapful.com
- else
  - if @product.belongs_to?(current_user)
    %h3
      = link_to "Products", products_path
      >
      = @product.name
    %h4= link_to "Edit", [:edit, @product]
    - if @product.use_hapful?
      .ui-tabs
        %ul
          %li= link_to "Details", "#details"
          %li= link_to "Logistics", "#logistics"
          /%li= link_to "Widget Customization", "#widget" //NOTE: disabled for now
        = render 'show_details'
        = render 'show_logistics'
        /= render 'show_widget_customization' //NOTE: disabled for now
    - else
      .ui-tabs
        %ul
          %li= link_to "Details", "#details"
      #details
        %table.zebra
          %tr
            %td Title
            %td.strong= @product.name
          %tr
            %td URL
            %td.strong= @product.post_url
          %tr
            %td Price
            %td.strong= number_to_currency(@product.price)

  - else
    = render 'products/buyer_view'
  

app/views/products/show.js.erb
function loadjscssfile(filename, filetype){
if (filetype=="js"){ //if filename is a external JavaScript file
var fileref=document.createElement('script')
fileref.setAttribute("type","text/javascript")
fileref.setAttribute("src", filename)
}
else if (filetype=="css"){ //if filename is an external CSS file
var fileref=document.createElement("link")
fileref.setAttribute("rel", "stylesheet")
fileref.setAttribute("type", "text/css")
fileref.setAttribute("href", filename)
}
if (typeof fileref!="undefined")
document.getElementsByTagName("head")[0].appendChild(fileref)
}

loadjscssfile("<%= ProjectConfig.value("site_url") %>/javascripts/hapful.js", "js")
loadjscssfile("<%= ProjectConfig.value("site_url") %>/stylesheets/colorbox.css", "css")
loadjscssfile("<%= ProjectConfig.value("site_url") %>/stylesheets/buttons.css", "css")

document.write("<%= @compiled_template.gsub("\n","").gsub("\"","\\\"") %>");