config/routes.rb
Hapful::Application.routes.draw do

  get "user_payment_methods/index"
  get "user_payment_methods/new"
  get "user_payment_methods/edit"
  get "paypal_accounts/index"
  get "paypal_accounts/edit"

  namespace :admin do 
    resources :categories
    resources :articles
    resources :payment_types
    resources :shipping_options
    resources :project_configs
    resources :users do
      member do
        post :tag
      end
    end
    resources :products
    resources :custom_emails
    root :to => 'dashboard#index'
  end

  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
  end

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  resources :users do
    member do
      get :change_password
      post :update_password
      get :merchant_detail
      match :update_merchant_detail
    end
    resources :user_merchant_accounts, :path=>:merchaccounts
    resources :user_payment_methods, :path=>:paygates
  end
  
  resources :taxes do
    collection do
      post :save
    end
  end

  resources :products do
    resources :product_widgets do
      member do
        get :preview
        get :iframed
      end
    end
    resources :comments do
      member do
        get :vote
      end
    end
    member do
      get :demo
    end
  end

  match '/posts/(:action)', :controller=>:posts

  resources :orders do
    member do
      get :change_state
    end
  end

  match '/my-dashboard' => 'users#dashboard', :as=>:user_dashboard

  match '/add-to-cart/:product_slug' =>'carts#add',   :as=>:add_to_cart
  match '/cart/cq/:product_slug/:change' =>'carts#change_quantity', :as=>:change_quantity
  match '/my-cart'                    =>'carts#show', :as=>:show_cart
  match '/trial' => 'pages#trial', :as=>:trial

  match  '/checkout/payment_state/:state'=> 'payments#set_state',               :as=>:set_payment_state
  match '/checkout/notice'            => 'payments#manual',                     :as=>:payment_notice
  get   '/checkout/payment'           => 'payments#new',                      :as=>:payment_checkout
  post  '/checkout/payment'           => 'payments#create',                   :as=>:do_payment_checkout
  get   '/checkout/complete_ppexpress'=> 'payments#complete_paypal_express',  :as=>:complete_paypal_express
  get   '/checkout/:merchant'         => 'orders#new',                        :as=>:checkout
  post  '/checkout/:merchant'         => 'orders#create',                     :as=>:build_order

  get '/track/:reference_number'    =>'pages#order_tracking', :as=>:order_tracking
  post '/track/:reference_number'    =>'pages#view_order_tracking', :as=>:view_order_tracking

  match '/update_merch' => 'pages#update_merch'
  match '/c/:id' => 'pages#by_category', :as=>:by_category
  match '/market' => 'pages#market', :as=>:market
  match '/search' => 'pages#search', :as=>:search
  match '/complete' => 'orders#completed', :as=>:completed_order
 
  match '/paypal-express' => 'payments#paypal_express', :as=>:paypal_express_checkout
  put '/redirect/:url' => 'pages#redirection'
  match '/p/:id' => 'products#show'
  match '/s/:seller'  =>'pages#seller', :as=>:seller_page
  match '/faqs' => 'pages#faqs', :as=>:faqs
  match '/privacy_policy' => 'pages#privacy_policy', :as=>:privacy_policy
  match '/terms' => 'pages#terms', :as=>:terms

  #  scope :protocol => 'https://', :constraints => { :protocol => 'https://' } do
  #    match '/paypal-express' => 'payments#paypal_express', :as=>:paypal_express_checkout
  #  end
  
  root :to=>'pages#index'

end

app/controllers/admin/payment_types_controller.rb
class Admin::PaymentTypesController < Admin::BaseController
  # GET /payment_types
  # GET /payment_types.xml
  def index
    @payment_types = PaymentType.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @payment_types }
    end
  end

  # GET /payment_types/1
  # GET /payment_types/1.xml
  def show
    @payment_type = PaymentType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @payment_type }
    end
  end

  # GET /payment_types/new
  # GET /payment_types/new.xml
  def new
    @payment_type = PaymentType.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @payment_type }
    end
  end

  # GET /payment_types/1/edit
  def edit
    @payment_type = PaymentType.find(params[:id])
  end

  # POST /payment_types
  # POST /payment_types.xml
  def create
    @payment_type = PaymentType.new(params[:payment_type])

    respond_to do |format|
      if @payment_type.save
        format.html { redirect_to([:admin, @payment_type], :notice => 'Payment type was successfully created.') }
        format.xml  { render :xml => @payment_type, :status => :created, :location => @payment_type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @payment_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /payment_types/1
  # PUT /payment_types/1.xml
  def update
    @payment_type = PaymentType.find(params[:id])

    respond_to do |format|
      if @payment_type.update_attributes(params[:payment_type])
        format.html { redirect_to([:admin, @payment_type], :notice => 'Payment type was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @payment_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_types/1
  # DELETE /payment_types/1.xml
  def destroy
    @payment_type = PaymentType.find(params[:id])
    @payment_type.destroy

    respond_to do |format|
      format.html { redirect_to(admin_payment_types_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/payment_types_helper.rb
module PaymentTypesHelper
end

app/views/admin/payment_types/_form.html.haml
= form_for [:admin, @payment_type] do |f|
  = render :partial=>"shared/form_errors", :locals=>{:object=>@payment_type}
  %p
    Name
    = f.text_field :name
  %p
    Activate
    = f.check_box :activated
  %p
    Requires Merchant Account
    = f.select :requisite_merchant_account, UserMerchantAccount::TYPES.collect{|k,v| [v,k]}, :include_blank=>true
  .actions
    = f.submit 'Save', :class=>"greenBtn"

app/views/admin/payment_types/edit.html.haml
= content_header("Edit Payment Type")
= content_for :content_header_right do
  = link_to 'Show', [:admin, @payment_type]
  \|
  = link_to 'Back', [:admin, :payment_types]
= render 'form'

app/views/admin/payment_types/index.html.haml
= content_header("Payment Type")
= content_for :content_header_right do
  = link_to 'New Payment type', new_admin_payment_type_path

.table
  %table
    %tr
      %th Name
      %th Enabled?
      %th{:colspan=>3} Options

    - @payment_types.each do |payment_type|
      %tr
        %td= payment_type.name
        %td= payment_type.activated? ? 'Yes' : 'No'
        %td
          = link_to 'Show', [:admin, payment_type]
          \|
          = link_to 'Edit', [:edit, :admin, payment_type]
          \|
          = link_to 'Destroy', [:admin, payment_type], :confirm => 'Are you sure?', :method => :delete
%br

app/views/admin/payment_types/new.html.haml
= content_header("New Payment Type")

= render 'form'

= link_to 'Back', admin_payment_types_path

app/views/admin/payment_types/show.html.haml
%p#notice= notice


= link_to 'Edit', [:edit, :admin, @payment_type]
\|
= link_to 'Back', admin_payment_types_path